# Generated by Django 5.2.4 on 2025-07-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catrgory',
            new_name='category',
        ),
    ]
